print("How old are you?", end=' ')
age = input()
print("How tall are you?", end=' ')
height = input()
print("How much do you weigh?", end=' ')
weight = input()
print("How cool are you? ")
coolness = input()
print("Are you happy?", end=' ')
happiness = input()

print(f"So, you're {age} old, {height} tall and {weight} heavy.")
print("So, you're {} old, {} tall and {} heavy.".format(age, height, weight))
print("Your coolness level is '{}' and your happiness level is '{}'.".format(coolness, happiness))
